#!/usr/bin/env python3
"""Generate the union of direct native-runtime bindings for the shipped cores."""
from pathlib import Path
import argparse
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent


def collect_imports(cores):
    imports = {}
    for core in cores:
        symbols = subprocess.check_output(['readelf', '--dyn-syms', '-W', str(core)], text=True)
        for line in symbols.splitlines():
            fields = line.split()
            if len(fields) < 8 or fields[6] != 'UND':
                continue
            name, kind = fields[7], fields[3]
            if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', name) or kind not in ('FUNC', 'OBJECT', 'NOTYPE'):
                raise ValueError(f'Unsupported native core import: {name} ({kind})')
            if name in imports and imports[name] != kind:
                raise ValueError(f'Conflicting native import types for {name}')
            imports[name] = kind
    return imports


def generate(imports):
    lines = ['// Generated by tools/core-imports.py; never edit.', '#include <cstring>']
    aliases = {'opendir': 'ps5_opendir', 'readdir': 'ps5_readdir', 'closedir': 'ps5_closedir',
               'dirfd': 'ps5_dirfd',
               'localtime_r': 'rtime_localtime', 'rewinddir': 'ps5_rewinddir',
               # src/core_threads_ps5.cpp: libkernel cannot attribute a thread
               # created from a core's stack, so a factory thread creates it.
               'pthread_create': 'ps5_core_pthread_create',
               # The same lookup runs in the thread-specific-data calls, which a
               # core's std::thread start routine makes itself.
               'pthread_key_create': 'ps5_core_pthread_key_create',
               'pthread_key_delete': 'ps5_core_pthread_key_delete',
               'pthread_getspecific': 'ps5_core_pthread_getspecific',
               'pthread_setspecific': 'ps5_core_pthread_setspecific',
               # src/memory_ps5.cpp: a core allocates from direct memory first, so
               # it cannot starve the libc heap the system libraries depend on.
               'malloc': 'ps5_core_malloc', 'calloc': 'ps5_core_calloc',
               'realloc': 'ps5_core_realloc', 'aligned_alloc': 'ps5_core_aligned_alloc',
               'posix_memalign': 'ps5_core_posix_memalign', 'strdup': 'ps5_core_strdup',
               '_Znwm': 'ps5_core_new', '_Znam': 'ps5_core_new',
               '_ZnwmRKSt9nothrow_t': 'ps5_core_new_nothrow',
               # src/libc_shims.c: the SDK resolves this import to nothing.
               'arc4random': 'ps5_arc4random',
               # src/libc_shims.c: the console libc's statvfs faults (it rests
               # on statfs, which only libkernel_sys carries).
               'statvfs': 'ps5_statvfs'}
    for index, (name, kind) in enumerate(sorted(imports.items())):
        target = aliases.get(name, name)
        declaration = f'void core_import_{index}()' if kind == 'FUNC' else f'char core_import_{index}[]'
        lines.append(f'extern "C" {declaration} asm("{target}");')
    lines.extend(['extern "C" void *ps5_core_import(const char *name)', '{'])
    for index, name in enumerate(sorted(imports)):
        lines.append(f'    if (!std::strcmp(name, "{name}")) return reinterpret_cast<void *>(&core_import_{index});')
    lines.extend(['    return nullptr;', '}'])
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('cores', type=Path, nargs='+')
    args = parser.parse_args()
    imports = collect_imports(args.cores)
    (ROOT / 'build/core_imports.inc').write_text(generate(imports))
    print(f'core imports: {len(imports)} explicit native bindings for {len(args.cores)} cores')


if __name__ == '__main__':
    main()
