#!/usr/bin/env python3
"""Generate direct native-runtime bindings for the built core's imports."""
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent
core = ROOT / 'build/cores/stage/cores/fceumm_libretro.so'
symbols = subprocess.check_output(['readelf', '--dyn-syms', '-W', str(core)], text=True)
imports = {}
for line in symbols.splitlines():
    fields = line.split()
    if len(fields) < 8 or fields[6] != 'UND':
        continue
    name, kind = fields[7], fields[3]
    if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', name) or kind not in ('FUNC', 'OBJECT'):
        raise SystemExit(f'Unsupported native core import: {name} ({kind})')
    imports[name] = kind

lines = ['// Generated by tools/core-imports.py; never edit.', '#include <cstring>']
aliases = {'opendir': 'ps5_opendir', 'readdir': 'ps5_readdir', 'closedir': 'ps5_closedir'}
for index, (name, kind) in enumerate(sorted(imports.items())):
    target = aliases.get(name, name)
    declaration = f'void core_import_{index}()' if kind == 'FUNC' else f'char core_import_{index}[]'
    lines.append(f'extern "C" {declaration} asm("{target}");')
lines.extend(['extern "C" void *ps5_core_import(const char *name)', '{'])
for index, name in enumerate(sorted(imports)):
    lines.append(f'    if (!std::strcmp(name, "{name}")) return reinterpret_cast<void *>(&core_import_{index});')
lines.extend(['    return nullptr;', '}'])
(ROOT / 'build/core_imports.inc').write_text('\n'.join(lines) + '\n')
print(f'core imports: {len(imports)} explicit native bindings generated')
