/*
 * PS5 RetroArch - the video driver, and the poke interface RGUI needs.
 *
 * Copyright (C) 2026 Mihawk
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * RetroArch asks a video driver for very little. From the interface report in
 * docs/REFERENCE.md, the mandatory surface is six members: `init`,
 * `suppress_screensaver`, `alive`, `frame`, `ident` and `poke_interface`. No
 * context driver is involved at all, and RGUI needs no GPU display context: it
 * rasterises the menu into its own framebuffer and hands that one texture to the
 * driver through `poke->set_texture_frame`, which this file implements.
 *
 * That is why this is the first menu to target: everything below it is the
 * display layer this project has already run on the console.
 *
 * The structs are filled POSITIONALLY, so field order is the interface. The
 * conditional members are honoured: `overlay_interface` exists only under
 * HAVE_OVERLAY and sits before `poke_interface`, and `gfx_widgets_enabled` exists
 * only under HAVE_GFX_WIDGETS. A build with widgets also needs a matching display
 * context, which RGUI does not, so widgets are a later step.
 */

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <new>

#include "display.hpp"
#include "trace.hpp"

/* RetroArch's own headers. `config.h` is generated by its build; until this
 * project runs that build, the driver is compiled against the tree with the
 * defines the build would set (see tools/build-raylib-free.sh). */
#include <gfx/video_defines.h>
#include <gfx/video_driver.h>

extern "C" int sceKernelUsleep(std::uint32_t microseconds);

namespace
{
using ps5::display::Display;

struct DriverState
{
    Display display;
    /* The menu's own framebuffer, handed over by set_texture_frame. */
    const void *menu_frame = nullptr;
    bool have_menu_frame = false;
    unsigned menu_width = 0;
    unsigned menu_height = 0;
    unsigned out_width = 0;
    unsigned out_height = 0;
    /* The menu framebuffer's format, as the frontend declared it: RGUI sends
     * RGB565 (rgb32 = false), a core may send RGB8888. */
    bool menu_rgb32 = false;
    /* The trace is a development aid; one line per fact is enough. */
    bool trace_texture_frame_done = false;
};

DriverState *state_of(void *data) noexcept
{
    return static_cast<DriverState *>(data);
}

/* --- video_driver_t ------------------------------------------------------- */

void *ps5_init(const video_info_t *video, input_driver_t **input, void **input_data) noexcept
{
    ps5::debug::mark_init("ps5_init entered", video != nullptr,
                          video ? static_cast<int>(video->width) : -1,
                          video ? static_cast<int>(video->height) : -1);

    auto *state = new (std::nothrow) DriverState();
    if (state == nullptr)
    {
        ps5::debug::mark("ps5_init: allocation failed");
        return nullptr;
    }

    state->out_width = video->width ? video->width : 1920;
    state->out_height = video->height ? video->height : 1080;

    /* The console's frame size is fixed by the registration in the display layer;
     * a request for another size is refused rather than silently scaled, so the
     * mismatch is visible here instead of on the screen. */
    if (!state->display.open(1920, 1080))
    {
        ps5::debug::mark("ps5_init: display.open refused the frame size");
        delete state;
        return nullptr;
    }
    ps5::debug::mark_value("ps5_init: display opened, back_surface width",
                           static_cast<long long>(state->display.back_surface().width));

    /* The driver owns no input: leaving these untouched hands input back to the
     * frontend's own driver, which is what this step is meant to test. */
    (void)input;
    (void)input_data;
    return state;
}

bool ps5_frame(void *data, const void *frame, unsigned width, unsigned height,
               std::uint64_t frame_count, unsigned pitch, const char *msg,
               video_frame_info_t *video_info) noexcept
{
    (void)frame_count;
    (void)msg;
    (void)video_info;
    // Cheap and decisive: if this line is on the console, the frontend reached
    // its first frame with this driver, and the question becomes what it drew.
    if (frame_count <= 1)
        ps5::debug::mark_value("ps5_frame first call, count", static_cast<long long>(frame_count));
    DriverState *state = state_of(data);
    if (state == nullptr)
        return false;

    const ps5::display::Surface surface = state->display.back_surface();

    /* What to show, in order of preference: the menu's framebuffer if RGUI has
     * handed one over, else the core's frame. The menu wins because at this step
     * the menu is the thing being proven. */
    const void *source = nullptr;
    unsigned source_width = 0;
    unsigned source_height = 0;
    unsigned source_pitch = 0;
    bool source_rgb32 = true;

    if (state->have_menu_frame && state->menu_frame != nullptr)
    {
        source = state->menu_frame;
        source_width = state->menu_width;
        source_height = state->menu_height;
        source_pitch = state->menu_width * (state->menu_rgb32 ? 4u : 2u);
        source_rgb32 = state->menu_rgb32;
    }
    else if (frame != nullptr && width != 0 && height != 0 && pitch != 0)
    {
        source = frame;
        source_width = width;
        source_height = height;
        source_pitch = pitch;
        /* A frame from a core is in the pixel format video_info_t asked for,
         * which this driver asks for as RGB8888. */
        source_rgb32 = true;
    }

    if (source == nullptr)
    {
        /* Nothing to show yet. A black frame still has to be presented, or the
         * display keeps the previous one and the console looks hung. */
        if (frame_count <= 2)
            ps5::debug::mark("ps5_frame: no source yet, presenting black");
        Display::clear(surface, 0xff000000u);
        const bool ok = state->display.present();
        if (frame_count <= 2)
            ps5::debug::mark_value("ps5_frame: black present returned", ok ? 1 : 0);
        return ok;
    }

    /* Nearest-neighbour scale into the console's frame, row by row through the
     * display layer's tiled addressing. The source is 4 bytes per pixel when the
     * frontend says rgb32 and 2 when it does not, so the two formats are read
     * where they are - a 16-bit frame read as 32-bit is a picture made of the
     * wrong halves of the right pixels, which looks like corruption rather than
     * like a format mistake. */
    const unsigned source_bytes = source_rgb32 ? 4u : 2u;
    for (unsigned y = 0; y < surface.height; ++y)
    {
        const unsigned source_y = (y * source_height) / surface.height;
        const auto *row = static_cast<const std::uint8_t *>(source) +
                          static_cast<std::size_t>(source_y) * source_pitch;
        for (unsigned x = 0; x < surface.width; ++x)
        {
            const unsigned source_x = (x * source_width) / surface.width;
            const auto *pixel = row + static_cast<std::size_t>(source_x) * source_bytes;
            std::uint32_t colour;
            if (source_rgb32)
            {
                colour = *reinterpret_cast<const std::uint32_t *>(pixel);
            }
            else
            {
                const auto rgb565 = *reinterpret_cast<const std::uint16_t *>(pixel);
                const std::uint32_t r = (rgb565 >> 11) & 0x1fu;
                const std::uint32_t g = (rgb565 >> 5) & 0x3fu;
                const std::uint32_t b = rgb565 & 0x1fu;
                colour = 0xff000000u | ((r << 3 | r >> 2) << 16) | ((g << 2 | g >> 4) << 8) |
                         (b << 3 | b >> 2);
            }
            Display::write(surface, x, y, colour);
        }
    }
    const bool presented = state->display.present();
    /* One line every few hundred frames: enough to see, from the console's own
     * file, that frames are being drawn, which branch they come from, and at what
     * size - without the trace growing with the frame count. Later rounds read
     * this to tell "the menu is up" from "the loop is spinning on a black frame"
     * without anyone needing to look at the television. */
    if (frame_count <= 2 || frame_count % 300 == 0)
    {
        char line[176];
        std::snprintf(line, sizeof(line), "ps5_frame %llu: %s %ux%u present=%d",
                      static_cast<unsigned long long>(frame_count),
                      state->have_menu_frame ? "menu" : "no-menu-source", source_width,
                      source_height, presented ? 1 : 0);
        ps5::debug::mark(line);
    }
    return presented;
}

bool ps5_alive(void *data) noexcept
{
    // The frontend ends its runloop the first time this answers false, and it
    // calls it only with the pointer init returned, so a null here means the
    // frontend lost the state rather than that the display closed.
    DriverState *state = state_of(data);
    const bool open = state != nullptr && state->display.is_open();
    if (!open)
        ps5::debug::mark(state == nullptr ? "ps5_alive: data was NULL"
                                          : "ps5_alive: the display is closed");
    return open;
}

bool ps5_suppress_screensaver(void *data, bool enable) noexcept
{
    /* The console's shell owns the screensaver and there is nothing here to
     * suppress, so the answer is always no. The member must exist because the
     * frontend calls it with no NULL check; see docs/REFERENCE.md. */
    (void)data;
    (void)enable;
    return false;
}

/* --- video_poke_interface_t ----------------------------------------------- */

void ps5_set_texture_frame(void *data, const void *frame, bool rgb32, unsigned width,
                           unsigned height, float alpha) noexcept
{
    (void)alpha;
    DriverState *state = state_of(data);
    /* rgb32 is kept, not filtered on. RGUI calls this with rgb32 = false - its
     * framebuffer is RGB565 - and an earlier version of this function returned
     * unless rgb32 was true, so the menu's pixels were dropped on every frame and
     * the driver fell back to presenting whatever the core had. The format is
     * recorded instead, and ps5_frame converts from it. */
    if (state == nullptr)
        return;
    state->menu_frame = frame;
    state->menu_width = width;
    state->menu_height = height;
    state->menu_rgb32 = rgb32;
    state->have_menu_frame = frame != nullptr && width != 0 && height != 0;
    if (!state->trace_texture_frame_done)
    {
        state->trace_texture_frame_done = true;
        char line[176];
        std::snprintf(line, sizeof(line), "ps5_set_texture_frame: rgb32=%d %ux%u frame=%s",
                      rgb32 ? 1 : 0, width, height, frame ? "present" : "NULL");
        ps5::debug::mark(line);
    }
}

void ps5_set_texture_enable(void *data, bool enable, bool full_screen) noexcept
{
    (void)full_screen;
    DriverState *state = state_of(data);
    if (state == nullptr)
        return;
    /* RGUI turns the texture off when a core is presenting its own frame. */
    state->have_menu_frame = enable && state->have_menu_frame;
}

void ps5_viewport_info(void *data, video_viewport_t *vp) noexcept
{
    DriverState *state = state_of(data);
    if (state == nullptr || vp == nullptr)
        return;
    vp->x = 0;
    vp->y = 0;
    vp->width = state->display.width();
    vp->height = state->display.height();
    vp->full_width = vp->width;
    vp->full_height = vp->height;
}

void ps5_get_video_output_size(void *data, unsigned *width, unsigned *height, char *s,
                               std::size_t len) noexcept
{
    (void)s;
    (void)len;
    DriverState *state = state_of(data);
    if (state == nullptr)
        return;
    if (width != nullptr)
        *width = state->display.width();
    if (height != nullptr)
        *height = state->display.height();
}

void ps5_set_video_mode(void *data, unsigned width, unsigned height, bool fullscreen) noexcept
{
    (void)data;
    (void)width;
    (void)height;
    (void)fullscreen;
}

static const video_poke_interface_t ps5_poke = {
    nullptr,                   /* get_flags */
    nullptr,                   /* load_texture */
    nullptr,                   /* unload_texture */
    ps5_set_video_mode,        /* set_video_mode */
    nullptr,                   /* get_refresh_rate */
    nullptr,                   /* set_filtering */
    ps5_get_video_output_size, /* get_video_output_size */
    nullptr,                   /* get_video_output_prev */
    nullptr,                   /* get_video_output_next */
    nullptr,                   /* get_current_framebuffer */
    nullptr,                   /* get_proc_address */
    nullptr,                   /* set_aspect_ratio */
    nullptr,                   /* apply_state_changes */
    ps5_set_texture_frame,     /* set_texture_frame */
    ps5_set_texture_enable,    /* set_texture_enable */
    nullptr,                   /* set_osd_msg */
    nullptr,                   /* show_mouse */
    nullptr,                   /* grab_mouse_toggle */
    nullptr,                   /* get_current_shader */
    nullptr,                   /* get_current_software_framebuffer */
    nullptr,                   /* get_hw_render_interface */
    nullptr,                   /* set_hdr_max_nits */
    nullptr,                   /* set_hdr_paper_white_nits */
    nullptr,                   /* set_hdr_contrast */
    nullptr,                   /* set_hdr_expand_gamut */
};

void ps5_get_poke_interface(void *data, const video_poke_interface_t **iface) noexcept
{
    (void)data;
    *iface = &ps5_poke;
}
} // namespace

/* The driver table. Positions are the interface; see the field list in
 * docs/REFERENCE.md. Conditional members are honoured so the same literal works
 * with or without HAVE_OVERLAY and HAVE_GFX_WIDGETS. */
/* C linkage: gfx/video_driver.c is C and names this symbol in its driver table. */
extern "C" video_driver_t video_ps5 = {
    ps5_init,
    ps5_frame,
    nullptr, /* set_nonblock_state */
    ps5_alive,
    nullptr, /* focus */
    ps5_suppress_screensaver,
    nullptr, /* has_windowed */
    nullptr, /* set_shader */
    nullptr, /* free */
    "ps5",
    nullptr, /* set_viewport */
    nullptr, /* set_rotation */
    ps5_viewport_info,
    nullptr, /* read_viewport */
    nullptr, /* read_frame_raw */
#ifdef HAVE_OVERLAY
    nullptr, /* overlay_interface */
#endif
    ps5_get_poke_interface,
#ifdef HAVE_GFX_WIDGETS
    nullptr, /* gfx_widgets_enabled */
#endif
    nullptr, /* wrap_type_to_enum: never called anywhere in the tree */
};
