/*
 * PS5 RetroArch - the video driver, and the poke interface RGUI needs.
 *
 * Copyright (C) 2026 Mihawk
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * RetroArch asks a video driver for very little. From the interface report in
 * docs/REFERENCE.md, the mandatory surface is six members: `init`,
 * `suppress_screensaver`, `alive`, `frame`, `ident` and `poke_interface`. No
 * context driver is involved at all, and RGUI needs no GPU display context: it
 * rasterises the menu into its own framebuffer and hands that one texture to the
 * driver through `poke->set_texture_frame`, which this file implements.
 *
 * That is why this is the first menu to target: everything below it is the
 * display layer this project has already run on the console.
 *
 * The structs are filled POSITIONALLY, so field order is the interface. The
 * conditional members are honoured: `overlay_interface` exists only under
 * HAVE_OVERLAY and sits before `poke_interface`, and `gfx_widgets_enabled` exists
 * only under HAVE_GFX_WIDGETS. A build with widgets also needs a matching display
 * context, which RGUI does not, so widgets are a later step.
 */

#include <cstddef>
#include <cstdint>
#include <new>

#include "display.hpp"

/* RetroArch's own headers. `config.h` is generated by its build; until this
 * project runs that build, the driver is compiled against the tree with the
 * defines the build would set (see tools/build-raylib-free.sh). */
#include <gfx/video_defines.h>
#include <gfx/video_driver.h>

extern "C" int sceKernelUsleep(std::uint32_t microseconds);

namespace
{
using ps5::display::Display;

struct DriverState
{
    Display display;
    /* The menu's own framebuffer, handed over by set_texture_frame. */
    const void *menu_frame = nullptr;
    bool have_menu_frame = false;
    unsigned menu_width = 0;
    unsigned menu_height = 0;
    unsigned out_width = 0;
    unsigned out_height = 0;
};

DriverState *state_of(void *data) noexcept
{
    return static_cast<DriverState *>(data);
}

/* --- video_driver_t ------------------------------------------------------- */

void *ps5_init(const video_info_t *video, input_driver_t **input, void **input_data) noexcept
{
    auto *state = new (std::nothrow) DriverState();
    if (state == nullptr)
        return nullptr;

    state->out_width = video->width ? video->width : 1920;
    state->out_height = video->height ? video->height : 1080;

    /* The console's frame size is fixed by the registration in the display layer;
     * a request for another size is refused rather than silently scaled, so the
     * mismatch is visible here instead of on the screen. */
    if (!state->display.open(1920, 1080))
    {
        delete state;
        return nullptr;
    }

    /* The driver owns no input: leaving these untouched hands input back to the
     * frontend's own driver, which is what this step is meant to test. */
    (void)input;
    (void)input_data;
    return state;
}

bool ps5_frame(void *data, const void *frame, unsigned width, unsigned height,
               std::uint64_t frame_count, unsigned pitch, const char *msg,
               video_frame_info_t *video_info) noexcept
{
    (void)frame_count;
    (void)msg;
    (void)video_info;
    DriverState *state = state_of(data);
    if (state == nullptr)
        return false;

    const ps5::display::Surface surface = state->display.back_surface();

    /* What to show, in order of preference: the menu's framebuffer if RGUI has
     * handed one over, else the core's frame. The menu wins because at this step
     * the menu is the thing being proven. */
    const void *source = nullptr;
    unsigned source_width = 0;
    unsigned source_height = 0;
    unsigned source_pitch = 0;

    if (state->have_menu_frame && state->menu_frame != nullptr)
    {
        source = state->menu_frame;
        source_width = state->menu_width;
        source_height = state->menu_height;
        source_pitch = state->menu_width * 4;
    }
    else if (frame != nullptr && width != 0 && height != 0)
    {
        source = frame;
        source_width = width;
        source_height = height;
        source_pitch = pitch;
    }

    if (source == nullptr)
    {
        /* Nothing to show yet. A black frame still has to be presented, or the
         * display keeps the previous one and the console looks hung. */
        Display::clear(surface, 0xff000000u);
        return state->display.present();
    }

    /* Nearest-neighbour scale into the console's frame, row by row through the
     * display layer's tiled addressing. */
    for (unsigned y = 0; y < surface.height; ++y)
    {
        const unsigned source_y = (y * source_height) / surface.height;
        const auto *row = static_cast<const std::uint8_t *>(source) +
                          static_cast<std::size_t>(source_y) * source_pitch;
        for (unsigned x = 0; x < surface.width; ++x)
        {
            const unsigned source_x = (x * source_width) / surface.width;
            const auto *pixel = reinterpret_cast<const std::uint32_t *>(row + source_x * 4);
            Display::write(surface, x, y, *pixel);
        }
    }
    return state->display.present();
}

bool ps5_alive(void *data) noexcept
{
    DriverState *state = state_of(data);
    return state != nullptr && state->display.is_open();
}

bool ps5_suppress_screensaver(void *data, bool enable) noexcept
{
    /* The console's shell owns the screensaver and there is nothing here to
     * suppress, so the answer is always no. The member must exist because the
     * frontend calls it with no NULL check; see docs/REFERENCE.md. */
    (void)data;
    (void)enable;
    return false;
}

/* --- video_poke_interface_t ----------------------------------------------- */

void ps5_set_texture_frame(void *data, const void *frame, bool rgb32, unsigned width,
                           unsigned height, float alpha) noexcept
{
    (void)alpha;
    DriverState *state = state_of(data);
    if (state == nullptr || !rgb32)
        return;
    state->menu_frame = frame;
    state->menu_width = width;
    state->menu_height = height;
    state->have_menu_frame = frame != nullptr;
}

void ps5_set_texture_enable(void *data, bool enable, bool full_screen) noexcept
{
    (void)full_screen;
    DriverState *state = state_of(data);
    if (state == nullptr)
        return;
    /* RGUI turns the texture off when a core is presenting its own frame. */
    state->have_menu_frame = enable && state->have_menu_frame;
}

void ps5_viewport_info(void *data, video_viewport_t *vp) noexcept
{
    DriverState *state = state_of(data);
    if (state == nullptr || vp == nullptr)
        return;
    vp->x = 0;
    vp->y = 0;
    vp->width = state->display.width();
    vp->height = state->display.height();
    vp->full_width = vp->width;
    vp->full_height = vp->height;
}

void ps5_get_video_output_size(void *data, unsigned *width, unsigned *height, char *s, std::size_t len) noexcept
{
    (void)s;
    (void)len;
    DriverState *state = state_of(data);
    if (state == nullptr)
        return;
    if (width != nullptr)
        *width = state->display.width();
    if (height != nullptr)
        *height = state->display.height();
}

void ps5_set_video_mode(void *data, unsigned width, unsigned height, bool fullscreen) noexcept
{
    (void)data;
    (void)width;
    (void)height;
    (void)fullscreen;
}

static const video_poke_interface_t ps5_poke = {
    nullptr,               /* get_flags */
    nullptr,               /* load_texture */
    nullptr,               /* unload_texture */
    ps5_set_video_mode,    /* set_video_mode */
    nullptr,               /* get_refresh_rate */
    nullptr,               /* set_filtering */
    ps5_get_video_output_size, /* get_video_output_size */
    nullptr,               /* get_video_output_prev */
    nullptr,               /* get_video_output_next */
    nullptr,               /* get_current_framebuffer */
    nullptr,               /* get_proc_address */
    nullptr,               /* set_aspect_ratio */
    nullptr,               /* apply_state_changes */
    ps5_set_texture_frame, /* set_texture_frame */
    ps5_set_texture_enable,/* set_texture_enable */
    nullptr,               /* set_osd_msg */
    nullptr,               /* show_mouse */
    nullptr,               /* grab_mouse_toggle */
    nullptr,               /* get_current_shader */
    nullptr,               /* get_current_software_framebuffer */
    nullptr,               /* get_hw_render_interface */
    nullptr,               /* set_hdr_max_nits */
    nullptr,               /* set_hdr_paper_white_nits */
    nullptr,               /* set_hdr_contrast */
    nullptr,               /* set_hdr_expand_gamut */
};

void ps5_get_poke_interface(void *data, const video_poke_interface_t **iface) noexcept
{
    (void)data;
    *iface = &ps5_poke;
}
} // namespace

/* The driver table. Positions are the interface; see the field list in
 * docs/REFERENCE.md. Conditional members are honoured so the same literal works
 * with or without HAVE_OVERLAY and HAVE_GFX_WIDGETS. */
video_driver_t video_ps5 = {
    ps5_init,
    ps5_frame,
    nullptr, /* set_nonblock_state */
    ps5_alive,
    nullptr, /* focus */
    ps5_suppress_screensaver,
    nullptr, /* has_windowed */
    nullptr, /* set_shader */
    nullptr, /* free */
    "ps5",
    nullptr, /* set_viewport */
    nullptr, /* set_rotation */
    ps5_viewport_info,
    nullptr, /* read_viewport */
    nullptr, /* read_frame_raw */
#ifdef HAVE_OVERLAY
    nullptr, /* overlay_interface */
#endif
    ps5_get_poke_interface,
#ifdef HAVE_GFX_WIDGETS
    nullptr, /* gfx_widgets_enabled */
#endif
    nullptr, /* wrap_type_to_enum: never called anywhere in the tree */
};
